

``` r
library(terra)
library(tidyterra)
library(tidyverse)
library(glue)

quants <- c(0.35, .5, .7)
scenarios <- c("rcp45", "rcp85")

projections_dir <- file.path("/media/smithers/shuysman/data/out/fire/")

test_file <- file.path(projections_dir, "Annual_sum_days_above_fire_risk_threshold_0.35_inmcm4_rcp85.nc")

near <- 2021:2040
mid <- 2041:2060
long <- 2081:2099

gye_boundary <- vect("/home/steve/OneDrive/whitebark/data/gyeboundary/GYE_boundary_dd.shp")

for (quant in quants) {
  for (scenario in scenarios) {
    projections <- rast(list.files(path = projections_dir,
                                  pattern = glue("Annual_sum_days_above_fire_risk_threshold_{quant}_.*_{scenario}.nc"),
                                  full.names = TRUE))

    ens <- terra::tapp(projections, fun = "mean", index = "years") %>%
      subst(NA, 0) ## Fill in holes in projections because zeroes filled as NA

    writeCDF(ens, file.path(projections_dir, glue("Annual_sum_days_above_fire_risk_threshold_{quant}_ensemble_{scenario}.nc")), overwrite = TRUE)

    for (period in list(near, mid, long)) {
      ens_period <- subset(ens, time(ens) %in% period)
      print(time(ens_period))
      ens_mean <- mean(ens_period)

      ens_mean_filename <- glue("Ensemble_mean_days_above_fire_risk_{quant}_{scenario}_{head(period, 1)}-{tail(period, 1)}.nc")
      writeCDF(ens_mean, file.path(projections_dir, ens_mean_filename), overwrite = TRUE)
      
    }
  }
}

```

```{r ens-plot}
ens_rcp45 <- rast(list.files(path = projections_dir,
                             pattern = "Ensemble_mean_days_above_fire_risk_0.35_rcp45.*.nc",
                             full.names = TRUE))
names(ens_rcp45) <- c("RCP4.5 2023-2040", "RCP4.5 2041-2060", "RCP4.5 2081-2099")

ens_rcp85 <- rast(list.files(path = projections_dir,
                             pattern = "Ensemble_mean_days_above_fire_risk_0.35_rcp85.*.nc",
                             full.names = TRUE))
names(ens_rcp85) <- c("RCP8.5 2023-2040", "RCP8.5 2041-2060", "RCP8.5 2081-2099")

ens <- c(ens_rcp45, ens_rcp85)

ggplot() +
  geom_spatraster(data = ens) +
  geom_sf(data = gye_boundary, fill = NA, linetype = "dotted", lwd = 1.5, color = "royalblue") +
  stat_spatraster(data = ens, aes(label = after_stat(round(value,0))), geom = "label", maxcell = 4, size = 4, alpha = 0.5) +
  facet_wrap(~lyr, ncol = 3) +
  scale_fill_viridis_c(name = "Mean days above dryness threshold", option = "inferno") +
  theme_bw()
  #ggtitle("Ensemble projections of wildfire risk in the GYE.  Quantile threshold = 0.35")
ggsave("img/Middle_Rockies/wildfire_risk_projections_gye.png", width = 10, height = 8)
```


```{r landfire}
landfire <- rast("/media/steve/storage/LANDFIRE/LF2020_EVT_220_CONUS/Tif/LC20_EVT_220.tif") %>%
  crop(project(gye_boundary, .))

##########
# Get the EVT_LF levels (category table)
evt_lf_levels <- levels(landfire$EVT_LF)[[1]]
head(evt_lf_levels) # Look at the first few rows

# To filter for a specific lifeform (e.g., Tree)
# Method 1: Using the numerical values representing the Tree category
tree_values <- evt_lf_levels$Value[evt_lf_levels$EVT_LF == "Tree"]
tree_raster <- ifel(landfire$EVT_LF %in% tree_values, landfire$EVT_LF, NA)

# Method 2: Creating a binary mask (1 for Tree, 0 for others)
tree_mask <- ifel(landfire$EVT_LF %in% tree_values, 1, 0)

# For multiple categories (e.g., Tree and Shrub)
tree_shrub_values <- evt_lf_levels$Value[evt_lf_levels$EVT_LF %in% c("Tree", "Shrub")]
tree_shrub_raster <- ifel(landfire$EVT_LF %in% tree_shrub_values, landfire$EVT_LF, NA)

# To get only unique EVT_LF categories
unique_categories <- unique(evt_lf_levels$EVT_LF)
print(unique_categories)

# To create a raster with all categories except certain ones (e.g., excluding Developed and Agriculture)
exclude_values <- evt_lf_levels$Value[evt_lf_levels$EVT_LF %in% c("Developed", "Agriculture")]
natural_veg_raster <- ifel(!(landfire$EVT_LF %in% exclude_values), landfire$EVT_LF, NA)

# To create separate rasters for each lifeform type
lifeform_types <- c("Tree", "Shrub", "Herb", "Sparse", "Barren", "Developed", "Agriculture", "Water", "Snow-Ice")
lifeform_rasters <- list()

for(lf in lifeform_types) {
  lf_values <- evt_lf_levels$Value[evt_lf_levels$EVT_LF == lf]
  if(length(lf_values) > 0) {
    lifeform_rasters[[lf]] <- ifel(landfire$EVT_LF %in% lf_values, 1, 0)
  }
}

# Visualize the results
plot(tree_raster, main="Tree Areas")
plot(tree_mask, main="Tree Mask (Binary)")
plot(lifeform_rasters[["Tree"]], main="Tree Areas (Binary)")
```
